Make default storage resettable
chrisguitarguy/RequestIdBundle pull request #28
Opened 2022-11-04 18:31 UTC by tourze

While in non-fpm runtime, like swoole, this service should be reset while init kernel.

2022-12-01 03:33 UTC, tourze commented
Any update?

2022-12-27 18:52 UTC, chrisguitarguy requested changes
:wave: sorry I didn't see this until now. One small thing with a return type.

> note that we advise making your services stateless instead of implementing this interface when possible.

That bit from the docblocks is also concerning.

Maybe a solution here would be to remove this bit: https://github.com/chrisguitarguy/RequestIdBundle/blob/28b78d0883eb8596762daed9fa3f58a14a59d425/src/EventListener/RequestIdListener.php#L102-L105

Instead of reseting things, just make sure we never re-use the request ID, thought that means that third parties can't hook in and set the request ID themselves. Not sure how used that would be.

Alternatively, having an on terminate event that sets the request ID to `null` is an option too.

2022-12-27 18:52 UTC, chrisguitarguy commented on src/SimpleIdStorage.php
> +    public function reset()
Can we add a `: void` return type here please?

2024-01-19 19:48 UTC, chrisguitarguy approved these changes

2024-01-19 19:48 UTC, merged